package org.segocode.webdl.system.util;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.stream.Stream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FileUtil {
    private static final Logger LOGGER = LoggerFactory.getLogger(FileUtil.class);

    /**
     * Deletes all files and folders within the 'downloads' folder.
     */
    public static void cleanDownloadsFolder() {
        cleanDirectory(Paths.get("./downloads/"));
    }

    static void cleanDirectory(Path directory) {
        if (Files.notExists(directory)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(directory)) {
            paths.sorted(Comparator.reverseOrder())
                    .filter(path -> !path.equals(directory))
                    .forEach(p -> {
                        try {
                            Files.delete(p);
                            LOGGER.info("Deleted: {}", p);
                        } catch (Exception e) {
                            LOGGER.error("Error deleting: {}", p, e);
                        }
                    });
        } catch (Exception e) {
            LOGGER.error("Error cleaning directory: {}", directory, e);
        }
    }

    /**
     * Locates the MP4 file generated by yt-dlp.
     *
     * @param filePath The path of the video file.
     * @return The video file if found or renamed successfully, null otherwise.
     */
    public static File locateVideoFile(String filePath) {
        Path video = Paths.get(filePath + ".mp4");
        return Files.isRegularFile(video) ? video.toFile() : null;
    }
}
